### PR TITLE
Toolbox toolbox config

### PR DESCRIPTION
**Pull request by benjamin-heasly**
Hi @DavidBrainard ,

Here is a PR to update configuration to take advantage of the new `tbUseProject()` in ToolboxToolbox.

The ToolboxToolbox `IBIOColorDetect.json` now includes IBIOColorDetect itself as a toolbox record.  This will allow ToolboxToolbox to do several things automatically at deployment time:
 - `git pull` to update IBIOColorDetect itself
 - copy `configuration/IBIOColorDetectLocalHookTemplate.m` to the local hooks folder, if missing
 - invoke the IBIOColorDetect local hook
 - add 4 subfolders of IBIOColorDetect to the Matlab path

`configuration/IBIOColorDetectLocalHookTemplate.m` was doing most of the above work "by hand".  I removed that code.  I also checked that by default, the local hook template chooses file paths based on `tbLocateProject()` and `tbUserFolder()`.  That way, the local hook can do something sane by default, even if the user never edits it.

### CODE REVIEW

**Comment by benjamin-heasly** [comment]
I tested this out locally on my laptop.  I was able to deploy.

I cloned IBIOColorDetect into my ToolboxToolbox projects folder, then did:
```
tbUseProject('IBIOColorDetect')
```

This seemed to work, except for some Matlab toolboxes that I don't have installed.
```
Error: "signal" had status -1, message "Could not locate the base directory for signal."
Error: "stats" had status -1, message "Could not locate the base directory for stats."
Error: "optim" had status -1, message "Could not locate the base directory for optim."
Error: "robotics" had status -1, message "Could not locate the base directory for robotics."
Error: "distcomp" had status -1, message "Could not locate the base directory for distcomp."
```

But I think that's OK for now.

**Comment by benjamin-heasly** [comment]
I was also able to run a validation with `IBIOCDValidateFullOne`.

As I read the output, the validation looks happy, and even succeeded in getting some remote validation data.
```
UnitTest will use preferences for the 'IBIOColorDetect' project

A set of existing preferences for project 'IBIOColorDetect' was found.


---------------------------------------------------------------------------
Available validation scripts                              Script no. 
---------------------------------------------------------------------------
basic
	v_IBIOCD1ConeCurrentEyeMovementsResponseInstances.m ....   1
	v_IBIOCD2ColorDetectFindPerformance.m ..................   2
	v_IBIOCDColorGabor.m ...................................   3
	v_IBIOCDConeIsomerizationsMovie.m ......................   4
compute
	v_BanksEtAlReplicate.m .................................   5

Enter script no. to validate/publish [1-5]: 3

------------------------------------------------------------------------------------------------------------
Running in 'FULLONLY' mode with 'rethrowExceptionAndAbort' runtime hehavior and verbosity level = 'high'.
Will validate 1 scripts.
------------------------------------------------------------------------------------------------------------

[  1] 'v_IBIOCDColorGabor'
	Internal validation  : PASSED
 	Run-time status      : no exception raised
	---------------------------------------------------------------------------------------------------------------------------------
	Ground truth  url    : http://52.32.77.154/repository/IBIOColorDetect/validation/full/basic/IBIOCDColorGabor/run00001/IBIOCDColorGabor-run00001-mat.mat
	Ground truth  localP : /home/ben/.gradle/caches/modules-2/files-2.1/validation.full.basic/IBIOCDColorGabor/run00001/bffe390191b4c8dafd47db65af1690e03a93c14b/IBIOCDColorGabor-run00001-mat.mat
	Full validation      : PASSED against ground truth data of 11-Nov-2016 16:42:48.
	 > Ground truth info :       eagleray.psych.upenn.edu / MACI64, MATLAB 9.0.0.341360 (R2016a) by 'dhb'
	 > Local host info   :             ben-ThinkPad-T450s / GLNXA64, MATLAB 9.0.0.341360 (R2016a) by 'ben'
	Note (*)             : script does not store any extra data.
	Validation report    : ***** v_IBIOCDColorGabor *****




 SUMMARY REPORT 
[  1] 'v_IBIOCDColorGabor': .......................................... [003.27 secs] Internal validation: PASSED ; Runtime status: NO EXCEPTION RAISED ; Fast validation: NoTest ; Full validation: PASSED ; 
```

So I think this looks happy.

How does it look on your end?

**Comment by DavidBrainard** [comment]
This seemed to work fine.  Merging and deleting branch.

**Comment by DavidBrainard** [comment]
The Matlab toolbox errors are probably good, since the project really does use routines in all of those toolboxes.  That is, they are in the json file precisely to declare these dependencies.

I guess it is an interesting question as to whether the declaration is best this way or done through a require hook.  This way has the feature that if you do a 'reset','no-matlab' you can then
check that no other toolbox dependencies have crept in.

**Comment by DavidBrainard** [comment]
Works like a charm.

DB

**Pull request merged**
